<?php

return [
    'SHOP_STATUS_INSTALLED' => 1,
    'SHOP_STATUS_UNINSTALLED' => 0,
    'FORM_STATUS_ACTIVE' => 1,
    'FORM_STATUS_INACTIVE' => 0,
    'AFTER_FORM_SUBMISSION_SHOW_MSG' => 1,
    'AFTER_FORM_SUBMISSION_REDIRECT_TO_PAGE' => 2,
    'ELEMENT_TYPE_TEXTFIELD' => 1,
    'ELEMENT_TYPE_EMAIL' => 2,
    'ELEMENT_TYPE_TEXTAREA' => 3,
    'ELEMENT_TYPE_DROPDOWN' => 4,
    'ELEMENT_TYPE_DATE' => 5,
    'ELEMENT_TYPE_CHECKBOX' => 6,
    'ELEMENT_TYPE_RADIO' => 7,
    'ELEMENT_TYPE_FILE' => 8,
    'ELEMENT_REQUIRED' => 1,
    'ELEMENT_NOT_REQUIRED' => 0,
    'ELEMENT_DEFAULT_CLASS_TEXTFIELD' => 'form-txt',
    'ELEMENT_DEFAULT_CLASS_DATE' => 'form-txt',
    'ELEMENT_DEFAULT_CLASS_DROPDOWN' => 'form-txt',
    'ELEMENT_DEFAULT_CLASS_EMAIL' => 'form-txt',
    'ELEMENT_DEFAULT_CLASS_TEXTAREA' => 'form-txt txt-area',
    'ELEMENT_DEFAULT_CLASS_FILE' => 'form-txt',
    'ELEMENT_ALLOW_MULTISELECT_DROPDOWN' => 1,
    'ELEMENT_NOT_ALLOW_MULTISELECT_DROPDOWN' => 0,
    'ELEMENT_DISPLAY_OPTIONS_SINGLE_LINE' => 0,
    'ELEMENT_DISPLAY_OPTIONS_NEW_LINE' => 1,
    'ELEMENT_TEXTAREA_DEFAULT_ROWS' => 10,
    
];

?>
